# -*- C++ -*-
# $Header$
# Authors: M.E. Monzani <monzani@slac.stanford.edu>
# Version: EngineeringModelRoot-05-00-00
Import('baseEnv')
Import('listFiles')
Import('packages')
progEnv = baseEnv.Clone()
#libEnv = baseEnv.Clone()   #  doesn't build a lib


progEnv.Tool('addLibrary', library = baseEnv['rootLibs'])
progEnv.Tool('commonRootDataLib')
progEnv.Tool('digiRootDataLib')
progEnv.Tool('mcRootDataLib')
progEnv.Tool('reconRootDataLib')
progEnv.Tool('identsLib')
progEnv.Tool('EventLib')

RunRootAnalyzer = progEnv.Program('RunRootAnalyzer', ['src/RunRootAnalyzer.cxx', 'src/RootAnalyzer.cxx', 'src/NtupleDef.cxx', 'src/ElecToGeo.cxx'])

progEnv.Tool('registerTargets', package = 'EngineeringModelRoot',
             binaryCxts = [[RunRootAnalyzer, progEnv]])





